/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppServicosRouteImport } from './routes/app.servicos'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppLojaRouteImport } from './routes/app.loja'
import { Route as AppConversasRouteImport } from './routes/app.conversas'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppAvaliacoesRouteImport } from './routes/app.avaliacoes'
import { Route as AppAgendarRouteImport } from './routes/app.agendar'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppLojaRoute = AppLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AppRoute,
} as any)
const AppConversasRoute = AppConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacoesRoute = AppAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendarRoute = AppAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/agendar': typeof AppAgendarRoute
  '/app/avaliacoes': typeof AppAvaliacoesRoute
  '/app/chat': typeof AppChatRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/loja': typeof AppLojaRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/agendar': typeof AppAgendarRoute
  '/app/avaliacoes': typeof AppAvaliacoesRoute
  '/app/chat': typeof AppChatRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/loja': typeof AppLojaRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/agendar': typeof AppAgendarRoute
  '/app/avaliacoes': typeof AppAvaliacoesRoute
  '/app/chat': typeof AppChatRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/loja': typeof AppLojaRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/agenda'
    | '/app/agendar'
    | '/app/avaliacoes'
    | '/app/chat'
    | '/app/conversas'
    | '/app/loja'
    | '/app/perfil'
    | '/app/servicos'
    | '/app/usuarios'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/agenda'
    | '/app/agendar'
    | '/app/avaliacoes'
    | '/app/chat'
    | '/app/conversas'
    | '/app/loja'
    | '/app/perfil'
    | '/app/servicos'
    | '/app/usuarios'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/agenda'
    | '/app/agendar'
    | '/app/avaliacoes'
    | '/app/chat'
    | '/app/conversas'
    | '/app/loja'
    | '/app/perfil'
    | '/app/servicos'
    | '/app/usuarios'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servicos': {
      id: '/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loja': {
      id: '/app/loja'
      path: '/loja'
      fullPath: '/app/loja'
      preLoaderRoute: typeof AppLojaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversas': {
      id: '/app/conversas'
      path: '/conversas'
      fullPath: '/app/conversas'
      preLoaderRoute: typeof AppConversasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avaliacoes': {
      id: '/app/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/app/avaliacoes'
      preLoaderRoute: typeof AppAvaliacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendar': {
      id: '/app/agendar'
      path: '/agendar'
      fullPath: '/app/agendar'
      preLoaderRoute: typeof AppAgendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAgendarRoute: typeof AppAgendarRoute
  AppAvaliacoesRoute: typeof AppAvaliacoesRoute
  AppChatRoute: typeof AppChatRoute
  AppConversasRoute: typeof AppConversasRoute
  AppLojaRoute: typeof AppLojaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppServicosRoute: typeof AppServicosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAgendarRoute: AppAgendarRoute,
  AppAvaliacoesRoute: AppAvaliacoesRoute,
  AppChatRoute: AppChatRoute,
  AppConversasRoute: AppConversasRoute,
  AppLojaRoute: AppLojaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppServicosRoute: AppServicosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
